version: 2.1

orbs:
  maven: circleci/maven@1.0.1

workflows:
  test:
    jobs:
      - maven/test: # checkout, build, test, and upload test results
          executor: 
            name: "maven/default"
            tag: "11.0.7"
